services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:c7dfc51dfb34aa4df01beb23069e1cadb0bb1bb7
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
