services:
  - name: cri-containerd
    image: linuxkitprojects/cri-containerd:2e3f5fcb87f92e1176637943b496910b9d979fb5
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
