services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:35f4761216380fe80a120ba7fa2d52545847cc13
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
