services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:b16c1a3f11b986d8f818d2797920db411ff51ac1
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
