services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:093735eea5b3d7488ffc5a0ecf83a08e344f2e4f
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
