services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:c4146c2fc5a91b6c46b7417305a958a0199f06af
    cgroupsPath: podruntime/runtime
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
