services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:6d7a253f3e69c506c76f0a0dfa32b7c307b0c9ee
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
