services:
  - name: cri-containerd
    image: linuxkitprojects/cri-containerd:5330c05b7eabba51d97af9d06204b7664e0719ef
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
