services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:456231d577a273334cee9b99761410cfc29d9811
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
