services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:179d9a1087d615f3a628e47a73243f8e56fb1440
    cgroupsPath: podruntime/runtime
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
