services:
  - name: cri-containerd
    image: linuxkitprojects/cri-containerd:afb7c111a40788b1e085856fbddacf8a878385e7
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
