services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:474d704f6dcb173b10768ab1d1bd61674468c7f9
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
