services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:3916819944f841f77d73bc622ccdddf1c5ff99e9
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
