services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:0a91a4e43787a89c0d4824ea71072e56a29bb833
    cgroupsPath: podruntime/runtime
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
