services:
  - name: cri-containerd
    image: linuxkitprojects/cri-containerd:2ff7dce33400a4d184976ca439725d8306295f1a
files:
  - path: /etc/kubelet.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
