services:
  - name: cri-containerd
    image: linuxkitprojects/cri-containerd:3ccc80f3257647a02c4a78fb0f0557805601c958
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
