services:
  - name: kubernetes-docker-image-cache-control-plane
    image: linuxkit/kubernetes-docker-image-cache-control-plane:b1bddee9fd3cfb73fad12408d5ca08136fd77889
    cgroupsPath: podruntime/control-cache
