kernel:
  image: linuxkit/kernel:4.9.38
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:059b2bb4b6efa5c58cf53fed4d0ea863521959fc
  - linuxkit/runc:4a35484aa6f90a1f06cdf1fb36f7056926a084b9
  - linuxkit/containerd:b6ffbb669248e3369081a6c4427026aa968a2385
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
  - name: sysfs
    image: linuxkit/sysfs:006a65b30cfdd9d751d7ab042fde7eca2c3bc9dc
  - name: binfmt
    image: linuxkit/binfmt:0bde4ebd422099f45c5ee03217413523ad2223e5
  - name: format
    image: linuxkit/format:84a997e69051a1bf05b7c1926ab785bb07932954
  - name: mounts
    image: linuxkit/mount:b24bd97ae43397b469dbaadd80f17f291c817bdf
    command: ["/mount.sh", "/var/lib/"]
  - name: var
    image: library/alpine:3.6
    command: ["mkdir", "/var/lib/kubeadm"]
    binds:
      - /var/lib:/var/lib
services:
  - name: getty
    image: linuxkit/getty:deb9332e786e72591bd9be200bcc9c7a534eb754
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: dhcpcd
    image: linuxkit/dhcpcd:4b7b8bb024cebb1bbb9c8026d44d7cbc8e202c41
  - name: ntpd
    image: linuxkit/openntpd:19370f5d9bec84eb91073b7196b732f1301d9c90
  - name: sshd
    image: linuxkit/sshd:89b2e91d7d1bf2f40220be0e3ed586e74746cceb
  - name: docker
    image: linuxkit/docker-ce:9b937df179bdbebbc70243779978057df0b54190
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /lib/modules:/lib/modules
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/etc/cni:rshared,rbind
     - /opt/cni:/opt/cni:rshared,rbind
    rootfsPropagation: shared
  - name: kubernetes-image-cache-common
    image: linuxkit/kubernetes:latest-image-cache-common
    binds:
      - /var/run:/var/run
  - name: kubernetes-image-cache-control-plane
    image: linuxkit/kubernetes:latest-image-cache-control-plane
    binds:
      - /var/run:/var/run
  - name: kubelet
    image: linuxkit/kubernetes:latest
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/rootfs/etc/cni:rshared,rbind
     - /opt/cni:/rootfs/opt/cni:rshared,rbind
    rootfsPropagation: shared
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - {path: etc/cni, directory: true}
  - {path: opt/cni, directory: true}
