kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:4fc8aa82ab34d62d510575c8fbe0c58b7ba9c480
  - linuxkit/runc:3a4e6cbf15470f62501b019b55e1caac5ee7689f
  - linuxkit/containerd:b1766e4c4c09f63ac4925a6e4612852a93f7e73b
  - linuxkit/ca-certificates:75cf419fb58770884c3464eb687ec8dfc704169d
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:b16a483897dd5f71be7e0c04cd090b05f52682e1"
  - name: sysfs
    image: linuxkit/sysfs:47367d0ef851e8bf2a9e2f80a05392c17f5c2c88
  - name: binfmt
    image: "linuxkit/binfmt:3433ade10a9271d4035f9424e8669358e425b6f6"
  - name: format
    image: "linuxkit/format:55afe08816c2a4d8dbae3ee51ef53e0bee422d66"
  - name: mounts
    image: "linuxkit/kubernetes:latest-mounts"
    capabilities:
     - all
    pid: host
    rootfsPropagation: shared
    binds:
     - /dev:/dev
     - /var:/var:rshared,rbind
services:
  - name: rngd
    image: "linuxkit/rngd:b67c3151a52b05db50e6207b40876900f2208d14"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:7d2f17a0e5d1ef9a75a527821a9ab0d753b22e7e"
  - name: ntpd
    image: "linuxkit/openntpd:ad834449a7eaf10dc022b3d8d2ed9faf7ec99d37"
  - name: sshd
    image: "linuxkit/sshd:ddce15b9fbde068941e31294acdcd22befa4fc20"
  - name: docker
    image: "linuxkit/docker-ce:668d62da6e3da081a8f8aca7db3e2a98adf5da59"
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /lib/modules:/lib/modules
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/etc/cni:rshared,rbind
     - /opt/cni:/opt/cni:rshared,rbind
    rootfsPropagation: shared
  - name: kubernetes-image-cache-common
    image: "linuxkit/kubernetes:latest-image-cache-common"
    binds:
      - /var/run:/var/run
  - name: kubernetes-image-cache-control-plane
    image: "linuxkit/kubernetes:latest-image-cache-control-plane"
    binds:
      - /var/run:/var/run
  - name: kubelet
    image: "linuxkit/kubernetes:latest"
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/rootfs/etc/cni:rshared,rbind
     - /opt/cni:/rootfs/opt/cni:rshared,rbind
    rootfsPropagation: shared
files:
  - path: root/.ssh/authorized_keys
    contents: '# Your ssh key goes here'
  - {path: etc/cni, directory: true}
  - {path: opt/cni, directory: true}
