kernel:
  image: linuxkit/kernel:4.9.54
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:98e95fb67e8afcf02c09ba927e4b357fec42977a
  - linuxkit/runc:991ef358ad8fc1111d64f4d8071f2009cc561f6a
  - linuxkit/containerd:eaf0d615cfceb9d854408dd3c80429ee8ac4d051
  - linuxkit/ca-certificates:ea3c4c120f929f4f07ac8535d75933365b5e9582
onboot:
  - name: sysctl
    image: linuxkit/sysctl:53f0c724919e8f76ea06c44ee703330290b22669
    binds:
     - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
    readonly: false
  - name: sysfs
    image: linuxkit/sysfs:7ff47034ed61c8e4c7ca5b8992056c66c6f39df8
  - name: dhcpcd
    image: linuxkit/dhcpcd:aa685261ceb2557990dcfe9dd8824c6b9ec416e2
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:4920d2b7f987c4cf67c5472308b0badcdfac4b2b
  - name: format
    image: linuxkit/format:e7f06bd9bb96b663f8aab7d648a5dfc3ed7785fc
  - name: mounts
    image: linuxkit/mount:80c6aeef04260eaa7c74a93594ea7c5a4ab2808e
    command: ["/usr/bin/mountie", "/var/lib/"]
services:
  - name: getty
    image: linuxkit/getty:7abaf7b276c59f80891d92e9279e3e3ee8e2f512
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:719e087b06dd14c29acd23fa07cccd036bbab4db
  - name: ntpd
    image: linuxkit/openntpd:8d32daf90ecf70b7e185cb7a2db53b4c539d371c
  - name: sshd
    image: linuxkit/sshd:4a2fc7be31fa57dcade391de6173e0af55296e7f
  - name: kubelet
    image: linuxkitprojects/kubernetes:6ec18b4e75dcf17c47887ece1848b63ddbe10230
files:
  - path: etc/linuxkit.yml
    metadata: yaml
  - path: /etc/kubernetes
    symlink: "/var/lib/kubeadm"
  - path: /usr/libexec/kubernetes/kubelet-plugins
    symlink: "/var/lib/kubelet-plugins"
  - path: /etc/kubeadm/kube-system.init/50-network.yaml
    source: network.yaml
  - path: /etc/sysctl.d/01-kubernetes.conf
    contents: 'net.ipv4.ip_forward = 1'
  - path: /opt/cni
    directory: true
  - path: /etc/cni
    directory: true
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
