kernel:
  image: linuxkit/kernel:4.9.39
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:838b772355a8690143b37de1cdd4ac5db725271f
  - linuxkit/runc:d5cbeb95bdafedb82ad2cf11cff1a5da7fcae630
  - linuxkit/containerd:e33e0534d6fca88e1eb86897a1ea410b4a5d722e
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
  - name: sysfs
    image: linuxkit/sysfs:006a65b30cfdd9d751d7ab042fde7eca2c3bc9dc
  - name: binfmt
    image: linuxkit/binfmt:0bde4ebd422099f45c5ee03217413523ad2223e5
  - name: metadata
    image: linuxkit/metadata:f5d4299909b159db35f72547e4ae70bd76c42c6c
  - name: format
    image: linuxkit/format:84a997e69051a1bf05b7c1926ab785bb07932954
  - name: mounts
    image: linuxkit/mount:ac8939c4102f97c084d9ddfd445c1908fce6d768
    command: ["/mount.sh", "/var/lib/"]
  - name: var
    image: library/alpine:3.6
    command: ["mkdir", "/var/lib/kubeadm"]
    binds:
      - /var/lib:/var/lib
services:
  - name: getty
    image: linuxkit/getty:894eef1e5f62f3bc31de8ffaff2b6c0e093c4595
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: dhcpcd
    image: linuxkit/dhcpcd:17423c1ccced74e3c005fd80486e8177841fe02b
  - name: ntpd
    image: linuxkit/openntpd:2874b66c9fa51fa5b4d11c8b50441eb94ee22a5a
  - name: sshd
    image: linuxkit/sshd:dc98a72c1d1285c30f2db176252f3ce2bf645d5b
  - name: docker
    image: docker:17.06.0-ce-dind
    capabilities:
     - all
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /lib/modules:/lib/modules
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/etc/cni:rshared,rbind
     - /opt/cni:/opt/cni:rshared,rbind
    rootfsPropagation: shared
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: kubernetes-image-cache-common
    image: linuxkitprojects/kubernetes-image-cache-common:d49a861bde872e6e975153a98a2c482834a30ef9
  - name: kubernetes-image-cache-control-plane
    image: linuxkitprojects/kubernetes-image-cache-control-plane:d49a861bde872e6e975153a98a2c482834a30ef9
  - name: kubelet
    image: linuxkitprojects/kubernetes:4f8c61254ff6243e93d5bb6315386ac66e94ed14
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - {path: etc/cni, directory: true}
  - {path: opt/cni, directory: true}
