org: linuxkit
image: kubelet
network: true
arches:
  - amd64
config:
  binds:
  - /dev:/dev
  - /etc/resolv.conf:/etc/resolv.conf
  - /etc/os-release:/etc/os-release
  - /run:/run:rshared,rbind
  - /var:/var:rshared,rbind
  - /var/lib/kubeadm:/etc/kubernetes
  - /etc/kubelet.sh.conf:/etc/kubelet.sh.conf
  - /etc/kubeadm:/etc/kubeadm
  - /var/lib/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins:rshared,rbind
  mounts:
  - type: cgroup
    options:
    - rw
    - nosuid
    - noexec
    - nodev
    - relatime
  capabilities:
  - all
  rootfsPropagation: shared
  pid: host
  runtime:
    mkdir:
    - /var/lib/kubeadm
    - /var/lib/cni/etc
    - /var/lib/cni/opt
    - /var/lib/kubelet-plugins
    mounts:
    - type: bind
      source: /var/lib/cni/opt
      destination: /opt/cni
      options:
      - rw
      - bind
    - type: bind
      source: /var/lib/cni/etc
      destination: /etc/cni
      options:
      - rw
      - bind
